### PR TITLE
CUQI Book Review - NABR

### LINKED ISSUE #42: Book review, by Nicolai
Description:
-------------
Go over the book material for review and light edits.

Definition of done:
--------------------
- [ ] A light edit of the book is done  
- [ ] The edits PR is reviewed
- [ ] The edits merged in the main incorporating the review comments
- [ ] Issues are created for more substantial edits if needed

### PR DESCRIPTION
**Pull request by nabriis**
Closes #42 

Context of review. Chapter 1 + Chapters A+B.

I like the structure established. Happy to update any notebook needed for the training.

In my review the Gibbs notebook needs a serious update. The rest look like they are in a good state.

I also reviewed Chapter 02, 03, quickly. Seems similar ot the notebook with some exceptions in chapter 03. We need to at least avoid the repetition there.

## Comments
1) I added some comments on some sections that need update. We need to update either in this PR or create issue to deal with it.
2) Perhaps this is personal preferance, but I was thinking perhaps the convolution forward model should be explained first rather than the heat equation. Also pre-running these notebooks would be tremendeously useful I think.

### CODE REVIEW

**Comment by nabriis** [comment]
Hi @amal-ghamdi. I reviewed the book material now. It looks really good. I had some general comments (see PR description). We need to agree on how to proceed with the strucutre and avoidign the repeated stuff in chapter 02 & 03 as in the training notebook.

**Review by amal-ghamdi — CHANGES_REQUESTED** [review]
Many thanks @nabriis. I made another PR #59 for you to review and merge if you agree. The PR #59 addresses some of your comments that you left in the book text. The comments that I did not address, I removed from the book text and I captured them in #58

**Comment by nabriis** [comment]
Great @amal-ghamdi. I approved the PR :)

**Review by amal-ghamdi — APPROVED** [review]
LGTM, thanks @nabriis!

**Pull request merged**
